 
 
 USE BD_LOCADORA_2DSIEM_2020;
 
 -- Questão 1
SELECT TB_AUTOMOVEL.TB_AUTOMOVEL_NOME,
       TB_MODELO.TB_MODELO_DESC,
       TB_MARCA.TB_MARCA_NOME
FROM TB_AUTOMOVEL INNER JOIN TB_MARCA
ON
TB_AUTOMOVEL.TB_MARCA_ID = TB_MARCA.TB_MARCA_ID
INNER JOIN TB_MODELO
ON
TB_MODELO.TB_MODELO_ID = TB_AUTOMOVEL.TB_MODELO_ID;

 

 -- Questão 2
                                                  
SELECT TB_MARCA.TB_MARCA_NOME, 
       COUNT(TB_AUTOMOVEL.TB_MARCA_ID) as TOTAL
FROM TB_AUTOMOVEL INNER JOIN TB_MARCA
ON
TB_AUTOMOVEL.TB_MARCA_ID = TB_MARCA.TB_MARCA_ID
GROUP BY TB_MARCA.TB_MARCA_NOME
ORDER BY TOTAL DESC;


-- Questão 3
SELECT TB_MODELO.TB_MODELO_DESC, 
       COUNT(TB_AUTOMOVEL.TB_MODELO_ID) as TOTAL
FROM TB_AUTOMOVEL INNER JOIN TB_MODELO
ON
TB_AUTOMOVEL.TB_MODELO_ID = TB_MODELO.TB_MODELO_ID
GROUP BY TB_MODELO.TB_MODELO_DESC
ORDER BY TOTAL DESC;

 

-- Questão 4
SELECT TB_MODELO.TB_MODELO_DESC,
       TB_MARCA.TB_MARCA_NOME,
       COUNT(TB_AUTOMOVEL.TB_MODELO_ID) as TOTAL
FROM TB_AUTOMOVEL INNER JOIN TB_MODELO
ON
TB_AUTOMOVEL.TB_MODELO_ID = TB_MODELO.TB_MODELO_ID
INNER JOIN TB_MARCA
ON
TB_AUTOMOVEL.TB_MARCA_ID = TB_MARCA.TB_MARCA_ID
GROUP BY TB_MODELO.TB_MODELO_DESC, TB_MARCA.TB_MARCA_NOME
ORDER BY TOTAL DESC;

 

 -- Questão 5
                                                
SELECT TB_CLIENTE_NOME, 
       COUNT(TB_LOCACAO.TB_CLIENTE_ID) as TOTAL
FROM TB_AUTOMOVEL INNER JOIN TB_LOCACAO
ON
TB_LOCACAO.TB_AUTOMOVEL_ID = TB_AUTOMOVEL.TB_AUTOMOVEL_ID
INNER JOIN TB_CLIENTE
ON
TB_CLIENTE.TB_CLIENTE_ID = TB_LOCACAO.TB_CLIENTE_ID
GROUP BY TB_CLIENTE_NOME
ORDER BY TOTAL DESC;

 

 -- Questão 6
SELECT TB_CLIENTE_NOME, 
       COUNT(TB_LOCACAO.TB_CLIENTE_ID) as TOTAL
FROM TB_AUTOMOVEL INNER JOIN TB_LOCACAO
ON
TB_LOCACAO.TB_AUTOMOVEL_ID = TB_AUTOMOVEL.TB_AUTOMOVEL_ID
INNER JOIN TB_CLIENTE
ON
TB_CLIENTE.TB_CLIENTE_ID = TB_LOCACAO.TB_CLIENTE_ID
GROUP BY TB_CLIENTE_NOME
ORDER BY TOTAL DESC LIMIT 1;

 -- Questão 7
SELECT TB_CLIENTE.TB_CLIENTE_NOME, 
       TB_AUTOMOVEL.TB_AUTOMOVEL_NOME,
       TB_MODELO.TB_MODELO_DESC,
       TB_MARCA.TB_MARCA_NOME
FROM TB_LOCACAO INNER JOIN TB_CLIENTE
ON
TB_LOCACAO.TB_CLIENTE_ID = TB_CLIENTE.TB_CLIENTE_ID
INNER JOIN TB_AUTOMOVEL
ON
TB_LOCACAO.TB_AUTOMOVEL_ID = TB_AUTOMOVEL.TB_AUTOMOVEL_ID
INNER JOIN TB_MODELO
ON
TB_AUTOMOVEL.TB_MODELO_ID = TB_MODELO.TB_MODELO_ID
INNER JOIN TB_MARCA
ON
TB_AUTOMOVEL.TB_MARCA_ID = TB_MARCA.TB_MARCA_ID
ORDER BY TB_CLIENTE_NOME ASC;
                                            
-- Questão 8
SELECT TB_AUTOMOVEL_NOME, 
       COUNT(TB_LOCACAO.TB_AUTOMOVEL_ID) as TOTAL
FROM TB_LOCACAO INNER JOIN TB_AUTOMOVEL
ON
TB_LOCACAO.TB_AUTOMOVEL_ID = TB_AUTOMOVEL.TB_AUTOMOVEL_ID
INNER JOIN TB_CLIENTE
ON
TB_CLIENTE.TB_CLIENTE_ID = TB_LOCACAO.TB_CLIENTE_ID
GROUP BY TB_AUTOMOVEL_NOME
ORDER BY TOTAL DESC;

 

-- Questão 9
SELECT TB_MARCA_NOME, 
       COUNT(TB_LOCACAO.TB_AUTOMOVEL_ID) as TOTAL
FROM TB_AUTOMOVEL INNER JOIN TB_MARCA
ON
TB_AUTOMOVEL.TB_MARCA_ID = TB_MARCA.TB_MARCA_ID
INNER JOIN TB_LOCACAO
ON
TB_LOCACAO.TB_AUTOMOVEL_ID =TB_AUTOMOVEL.TB_AUTOMOVEL_ID  
GROUP BY TB_MARCA_NOME
ORDER BY TOTAL DESC LIMIT 2;

 

-- Questão 10
SELECT TB_MODELO_DESC, 
       COUNT(TB_LOCACAO.TB_AUTOMOVEL_ID) as TOTAL
FROM TB_AUTOMOVEL INNER JOIN TB_MODELO
ON
TB_AUTOMOVEL.TB_MODELO_ID = TB_MODELO.TB_MODELO_ID
INNER JOIN TB_LOCACAO
ON
TB_LOCACAO.TB_AUTOMOVEL_ID =TB_AUTOMOVEL.TB_AUTOMOVEL_ID  
GROUP BY TB_MODELO_DESC
ORDER BY TOTAL DESC LIMIT 1;

 

-- Questão 11
SELECT TB_AUTOMOVEL.TB_AUTOMOVEL_NOME
FROM TB_AUTOMOVEL INNER JOIN TB_LOCACAO
ON
TB_AUTOMOVEL.TB_AUTOMOVEL_ID = TB_LOCACAO.TB_AUTOMOVEL_ID
GROUP BY TB_LOCACAO_DT_FIM
ORDER BY TB_LOCACAO.TB_LOCACAO_DT_FIM DESC LIMIT 1;